device: auto
num_workers: 10
seed: 0
batch_size: 100
dataset: cifar10
attack: badnet
model: vit_tiny
target_label: 0
pratio: 0.1
defense_data: 500

lr: 0.00002
lr1: 0.00005
momentum: 0.9
weight_decay: 0.00005 #0.00002
epochs: 1
interval: 10
multi_gpu: False

# prune
lr_mask: 0.2
penalty: 0.0005